### PR TITLE
avb_1722_maap: bugfix for maap_conflict().

### PR DESCRIPTION
**Pull request by andrew-elder**
Conditional for determining conflict did not correctly
handle the case where addr->range > 1. Rewritten to
iterate over every address in an address range.

### CODE REVIEW

**Comment by ajwlucas** [comment]
Hi Andrew, 

Do you have a unit test for this fix? Or did you discover it by inspection?

**Comment by andrew-elder** [comment]
On 6/29/2012 11:46 AM, Andy Lucas wrote:

> Hi Andrew,
> 
> Do you have a unit test for this fix? Or did you discover it by inspection?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/xcore/sw_avb/pull/9#issuecomment-6665558
> 
> Hi Andy,

By inspection,. Sorry, no unit test yet.

## 

Andrew Elder
AudioScience, Inc.
+1-585-271-8870
www.audioscience.com

**Comment by ajwlucas** [comment]
OK, thanks Andrew. I will try and put together some tests and merge the pull request.

**Comment by ajwlucas** [comment]
Hi Andrew, 

I'm closing this now that I've rewritten MAAP to correctly handle this case. Let me know if you have any issues.

**Comment by andrew-elder** [comment]
On 9/6/2012 8:29 AM, Andy Lucas wrote:

> Hi Andrew,
> 
> I'm closing this now that I've rewritten MAAP to correctly handle this 
> case. Let me know if you have any issues.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/xcore/sw_avb/pull/9#issuecomment-8330549.

Ok by me.

## 

Andrew Elder
AudioScience, Inc.
+1-585-271-8870
www.audioscience.com

**Pull request closed without merging**
